// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: api/brainianc-browl.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// playerStatus status
type PlayerStatus int32

const (
	PlayerStatus_PLAYING      PlayerStatus = 0
	PlayerStatus_WAITING      PlayerStatus = 1
	PlayerStatus_DISCONNECTED PlayerStatus = 2
)

// Enum value maps for PlayerStatus.
var (
	PlayerStatus_name = map[int32]string{
		0: "PLAYING",
		1: "WAITING",
		2: "DISCONNECTED",
	}
	PlayerStatus_value = map[string]int32{
		"PLAYING":      0,
		"WAITING":      1,
		"DISCONNECTED": 2,
	}
)

func (x PlayerStatus) Enum() *PlayerStatus {
	p := new(PlayerStatus)
	*p = x
	return p
}

func (x PlayerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_brainianc_browl_proto_enumTypes[0].Descriptor()
}

func (PlayerStatus) Type() protoreflect.EnumType {
	return &file_api_brainianc_browl_proto_enumTypes[0]
}

func (x PlayerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerStatus.Descriptor instead.
func (PlayerStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_brainianc_browl_proto_rawDescGZIP(), []int{0}
}

// GamePlayStatus status
type GamePlayStatus int32

const (
	GamePlayStatus_ON_GOING    GamePlayStatus = 0
	GamePlayStatus_GAME_OVER   GamePlayStatus = 1
	GamePlayStatus_NOT_STARTED GamePlayStatus = 2
)

// Enum value maps for GamePlayStatus.
var (
	GamePlayStatus_name = map[int32]string{
		0: "ON_GOING",
		1: "GAME_OVER",
		2: "NOT_STARTED",
	}
	GamePlayStatus_value = map[string]int32{
		"ON_GOING":    0,
		"GAME_OVER":   1,
		"NOT_STARTED": 2,
	}
)

func (x GamePlayStatus) Enum() *GamePlayStatus {
	p := new(GamePlayStatus)
	*p = x
	return p
}

func (x GamePlayStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GamePlayStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_brainianc_browl_proto_enumTypes[1].Descriptor()
}

func (GamePlayStatus) Type() protoreflect.EnumType {
	return &file_api_brainianc_browl_proto_enumTypes[1]
}

func (x GamePlayStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GamePlayStatus.Descriptor instead.
func (GamePlayStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_brainianc_browl_proto_rawDescGZIP(), []int{1}
}

// Gameplay command contains the actual answer to the question. And server returns
// the result of the answer.
type GamePlayCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// answer given by the player
	PlayerAnswer string `protobuf:"bytes,2,opt,name=player_answer,json=playerAnswer,proto3" json:"player_answer,omitempty"`
	// question
	Question string `protobuf:"bytes,3,opt,name=question,proto3" json:"question,omitempty"`
	// actual answer
	CorrectAnswer string `protobuf:"bytes,4,opt,name=correct_answer,json=correctAnswer,proto3" json:"correct_answer,omitempty"`
	// timestamp question was asked
	QuestionTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=question_time,json=questionTime,proto3" json:"question_time,omitempty"`
}

func (x *GamePlayCommand) Reset() {
	*x = GamePlayCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_brainianc_browl_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GamePlayCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GamePlayCommand) ProtoMessage() {}

func (x *GamePlayCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_brainianc_browl_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GamePlayCommand.ProtoReflect.Descriptor instead.
func (*GamePlayCommand) Descriptor() ([]byte, []int) {
	return file_api_brainianc_browl_proto_rawDescGZIP(), []int{0}
}

func (x *GamePlayCommand) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GamePlayCommand) GetPlayerAnswer() string {
	if x != nil {
		return x.PlayerAnswer
	}
	return ""
}

func (x *GamePlayCommand) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *GamePlayCommand) GetCorrectAnswer() string {
	if x != nil {
		return x.CorrectAnswer
	}
	return ""
}

func (x *GamePlayCommand) GetQuestionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.QuestionTime
	}
	return nil
}

// Player is a game player
type Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Score  int32        `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	Name   string       `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	IsBot  bool         `protobuf:"varint,4,opt,name=is_bot,json=isBot,proto3" json:"is_bot,omitempty"`
	Status PlayerStatus `protobuf:"varint,5,opt,name=status,proto3,enum=api.PlayerStatus" json:"status,omitempty"`
}

func (x *Player) Reset() {
	*x = Player{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_brainianc_browl_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_api_brainianc_browl_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_api_brainianc_browl_proto_rawDescGZIP(), []int{1}
}

func (x *Player) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Player) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetIsBot() bool {
	if x != nil {
		return x.IsBot
	}
	return false
}

func (x *Player) GetStatus() PlayerStatus {
	if x != nil {
		return x.Status
	}
	return PlayerStatus_PLAYING
}

// GameSummary is a message sent after the game is over
type GameSummary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Players []*Player `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	Winner  *Player   `protobuf:"bytes,3,opt,name=winner,proto3" json:"winner,omitempty"`
	IsOver  bool      `protobuf:"varint,4,opt,name=is_over,json=isOver,proto3" json:"is_over,omitempty"`
}

func (x *GameSummary) Reset() {
	*x = GameSummary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_brainianc_browl_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameSummary) ProtoMessage() {}

func (x *GameSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_brainianc_browl_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameSummary.ProtoReflect.Descriptor instead.
func (*GameSummary) Descriptor() ([]byte, []int) {
	return file_api_brainianc_browl_proto_rawDescGZIP(), []int{2}
}

func (x *GameSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GameSummary) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *GameSummary) GetWinner() *Player {
	if x != nil {
		return x.Winner
	}
	return nil
}

func (x *GameSummary) GetIsOver() bool {
	if x != nil {
		return x.IsOver
	}
	return false
}

// A GamePlay is a message sent while playing
type GamePlay struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code   string         `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Player *Player        `protobuf:"bytes,3,opt,name=player,proto3" json:"player,omitempty"`
	Status GamePlayStatus `protobuf:"varint,4,opt,name=status,proto3,enum=api.GamePlayStatus" json:"status,omitempty"`
	// Types that are assignable to Cmd:
	//
	//	*GamePlay_Summary
	//	*GamePlay_Command
	Cmd isGamePlay_Cmd `protobuf_oneof:"cmd"`
}

func (x *GamePlay) Reset() {
	*x = GamePlay{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_brainianc_browl_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GamePlay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GamePlay) ProtoMessage() {}

func (x *GamePlay) ProtoReflect() protoreflect.Message {
	mi := &file_api_brainianc_browl_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GamePlay.ProtoReflect.Descriptor instead.
func (*GamePlay) Descriptor() ([]byte, []int) {
	return file_api_brainianc_browl_proto_rawDescGZIP(), []int{3}
}

func (x *GamePlay) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GamePlay) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GamePlay) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *GamePlay) GetStatus() GamePlayStatus {
	if x != nil {
		return x.Status
	}
	return GamePlayStatus_ON_GOING
}

func (m *GamePlay) GetCmd() isGamePlay_Cmd {
	if m != nil {
		return m.Cmd
	}
	return nil
}

func (x *GamePlay) GetSummary() *GameSummary {
	if x, ok := x.GetCmd().(*GamePlay_Summary); ok {
		return x.Summary
	}
	return nil
}

func (x *GamePlay) GetCommand() *GamePlayCommand {
	if x, ok := x.GetCmd().(*GamePlay_Command); ok {
		return x.Command
	}
	return nil
}

type isGamePlay_Cmd interface {
	isGamePlay_Cmd()
}

type GamePlay_Summary struct {
	Summary *GameSummary `protobuf:"bytes,5,opt,name=summary,proto3,oneof"`
}

type GamePlay_Command struct {
	Command *GamePlayCommand `protobuf:"bytes,6,opt,name=command,proto3,oneof"`
}

func (*GamePlay_Summary) isGamePlay_Cmd() {}

func (*GamePlay_Command) isGamePlay_Cmd() {}

var File_api_brainianc_browl_proto protoreflect.FileDescriptor

var file_api_brainianc_browl_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x61, 0x6e, 0x63, 0x2d,
	0x62, 0x72, 0x6f, 0x77, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xca, 0x01, 0x0a, 0x0f, 0x47, 0x61, 0x6d, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f,
	0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x63,
	0x74, 0x5f, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x63, 0x6f, 0x72, 0x72, 0x65, 0x63, 0x74, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x3f, 0x0a,
	0x0d, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x0c, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x84,
	0x01, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f,
	0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x69, 0x73, 0x5f, 0x62, 0x6f, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x69, 0x73, 0x42, 0x6f, 0x74, 0x12, 0x29, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x82, 0x01, 0x0a, 0x0b, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x75,
	0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x25, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12, 0x23, 0x0a, 0x06,
	0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x06, 0x77, 0x69, 0x6e, 0x6e, 0x65,
	0x72, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x6f, 0x76, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x4f, 0x76, 0x65, 0x72, 0x22, 0xe7, 0x01, 0x0a, 0x08, 0x47,
	0x61, 0x6d, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x23, 0x0a, 0x06, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x12, 0x2b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2c, 0x0a,
	0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79,
	0x48, 0x00, 0x52, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x30, 0x0a, 0x07, 0x63,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x48, 0x00, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x42, 0x05, 0x0a,
	0x03, 0x63, 0x6d, 0x64, 0x2a, 0x3a, 0x0a, 0x0c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x4c, 0x41, 0x59, 0x49, 0x4e, 0x47, 0x10,
	0x00, 0x12, 0x0b, 0x0a, 0x07, 0x57, 0x41, 0x49, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x10,
	0x0a, 0x0c, 0x44, 0x49, 0x53, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x45, 0x44, 0x10, 0x02,
	0x2a, 0x3e, 0x0a, 0x0e, 0x47, 0x61, 0x6d, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x0c, 0x0a, 0x08, 0x4f, 0x4e, 0x5f, 0x47, 0x4f, 0x49, 0x4e, 0x47, 0x10, 0x00,
	0x12, 0x0d, 0x0a, 0x09, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x4f, 0x56, 0x45, 0x52, 0x10, 0x01, 0x12,
	0x0f, 0x0a, 0x0b, 0x4e, 0x4f, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x52, 0x54, 0x45, 0x44, 0x10, 0x02,
	0x32, 0x3b, 0x0a, 0x0d, 0x42, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x61, 0x63, 0x42, 0x72, 0x61, 0x77,
	0x6c, 0x12, 0x2a, 0x0a, 0x04, 0x50, 0x6c, 0x61, 0x79, 0x12, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x47, 0x61, 0x6d, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x1a, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47,
	0x61, 0x6d, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x2b, 0x5a,
	0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x68, 0x69, 0x6e,
	0x6d, 0x61, 0x79, 0x62, 0x2f, 0x62, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x61, 0x63, 0x2d, 0x62, 0x72,
	0x61, 0x77, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_api_brainianc_browl_proto_rawDescOnce sync.Once
	file_api_brainianc_browl_proto_rawDescData = file_api_brainianc_browl_proto_rawDesc
)

func file_api_brainianc_browl_proto_rawDescGZIP() []byte {
	file_api_brainianc_browl_proto_rawDescOnce.Do(func() {
		file_api_brainianc_browl_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_brainianc_browl_proto_rawDescData)
	})
	return file_api_brainianc_browl_proto_rawDescData
}

var file_api_brainianc_browl_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_brainianc_browl_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_brainianc_browl_proto_goTypes = []interface{}{
	(PlayerStatus)(0),             // 0: api.PlayerStatus
	(GamePlayStatus)(0),           // 1: api.GamePlayStatus
	(*GamePlayCommand)(nil),       // 2: api.GamePlayCommand
	(*Player)(nil),                // 3: api.Player
	(*GameSummary)(nil),           // 4: api.GameSummary
	(*GamePlay)(nil),              // 5: api.GamePlay
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_api_brainianc_browl_proto_depIdxs = []int32{
	6, // 0: api.GamePlayCommand.question_time:type_name -> google.protobuf.Timestamp
	0, // 1: api.Player.status:type_name -> api.PlayerStatus
	3, // 2: api.GameSummary.players:type_name -> api.Player
	3, // 3: api.GameSummary.winner:type_name -> api.Player
	3, // 4: api.GamePlay.player:type_name -> api.Player
	1, // 5: api.GamePlay.status:type_name -> api.GamePlayStatus
	4, // 6: api.GamePlay.summary:type_name -> api.GameSummary
	2, // 7: api.GamePlay.command:type_name -> api.GamePlayCommand
	5, // 8: api.BrainiacBrawl.Play:input_type -> api.GamePlay
	5, // 9: api.BrainiacBrawl.Play:output_type -> api.GamePlay
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_api_brainianc_browl_proto_init() }
func file_api_brainianc_browl_proto_init() {
	if File_api_brainianc_browl_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_brainianc_browl_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GamePlayCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_brainianc_browl_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Player); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_brainianc_browl_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameSummary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_brainianc_browl_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GamePlay); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_brainianc_browl_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*GamePlay_Summary)(nil),
		(*GamePlay_Command)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_brainianc_browl_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_brainianc_browl_proto_goTypes,
		DependencyIndexes: file_api_brainianc_browl_proto_depIdxs,
		EnumInfos:         file_api_brainianc_browl_proto_enumTypes,
		MessageInfos:      file_api_brainianc_browl_proto_msgTypes,
	}.Build()
	File_api_brainianc_browl_proto = out.File
	file_api_brainianc_browl_proto_rawDesc = nil
	file_api_brainianc_browl_proto_goTypes = nil
	file_api_brainianc_browl_proto_depIdxs = nil
}
